[package]
name = "plex-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }

[dev-dependencies]
rand = "0.9.1"
tempfile = "3.20.0"
